version: '3.2'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=pros'
      - 'POSTGRES_PASSWORD=foobar'
      - 'POSTGRES_DB=kup'
  api:
    build: .
    container_name: api
    ports:
      - "8080:8000"
    volumes:
      - ./src:/usr/api/src
    depends_on:
      - postgres
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    links:
      - postgres
    environment:
      - 'PGHOST=postgres'
      - 'PGDATABASE=kup'
      - 'PGUSER=pros'
      - 'PGPASSWORD=foobar'
    
  
